""" Project Euler Problem 2 - https://projecteuler.net/problem=2
 * Even Fibonacci numbers
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 *
 * Created by Harvey Chen on 10/10/2015.
 * Copyright (c) 2015 Harvey Chen. All rights reserved.
"""
fib1 = 2
fib2 = 1
fib = fib2 + fib1
sum = 2
while (fib < 4000000):
    if (fib % 2 == 0):
        sum += fib
    fib = fib1 + fib2
    fib2 = fib1
    fib1 = fib
print(sum)

#Ans: 4613732
